# Generated by Django 5.0.2 on 2024-02-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='Unmergeimages/'),
        ),
    ]
