# Generated by Django 5.0.2 on 2024-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0003_mergeimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmergeImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unmerge_secret_img', models.CharField(max_length=100)),
                ('secretimage', models.ImageField(default=None, max_length=250, null=True, upload_to='mergeimages/')),
                ('unmerge_cover_img', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(default=None, max_length=250, null=True, upload_to='mergeimages/')),
            ],
        ),
    ]
