# Generated by Django 5.0.2 on 2024-03-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0004_unmergeimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=100)),
                ('secret_text', models.ImageField(default=None, max_length=250, null=True, upload_to='MergeText/')),
                ('cover', models.CharField(max_length=100)),
                ('cover_text', models.ImageField(default=None, max_length=250, null=True, upload_to='MergeText/')),
            ],
        ),
        migrations.CreateModel(
            name='UnmergeTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unmerge_secret_img', models.CharField(max_length=100)),
                ('secretimage', models.ImageField(default=None, max_length=250, null=True, upload_to='UnmergeText/')),
                ('unmerge_cover_img', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(default=None, max_length=250, null=True, upload_to='UnmergeText/')),
            ],
        ),
        migrations.AlterField(
            model_name='unmergeimagemodel',
            name='cover_image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='Unmergeimages/'),
        ),
        migrations.AlterField(
            model_name='unmergeimagemodel',
            name='secretimage',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='Unmergeimages/'),
        ),
    ]
