# Generated by Django 5.0.2 on 2024-03-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0005_mergetextmodel_unmergetextmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unmergetextmodel',
            old_name='cover_image',
            new_name='cover_text',
        ),
        migrations.RenameField(
            model_name='unmergetextmodel',
            old_name='secretimage',
            new_name='secrettext',
        ),
        migrations.RenameField(
            model_name='unmergetextmodel',
            old_name='unmerge_cover_img',
            new_name='unmerge_cover_text',
        ),
        migrations.RenameField(
            model_name='unmergetextmodel',
            old_name='unmerge_secret_img',
            new_name='unmerge_secret_text',
        ),
    ]
