# Generated by Django 5.0.2 on 2024-03-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0006_rename_cover_image_unmergetextmodel_cover_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeAudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=100)),
                ('secret_audio', models.ImageField(default=None, max_length=250, null=True, upload_to='MergeAudio/')),
                ('cover', models.CharField(max_length=100)),
                ('cover_audio', models.ImageField(default=None, max_length=250, null=True, upload_to='MergeAudio/')),
            ],
        ),
        migrations.CreateModel(
            name='UnmergeAudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unmerge_secret_audio', models.CharField(max_length=100)),
                ('secretaudio', models.ImageField(default=None, max_length=250, null=True, upload_to='UnmergeAudio/')),
                ('unmerge_cover_audio', models.CharField(max_length=100)),
                ('cover_audio', models.ImageField(default=None, max_length=250, null=True, upload_to='UnmergeAudio/')),
            ],
        ),
    ]
